package itson.presentacion.frames;

import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author victoria
 */
public class FrmPantallaInicio extends javax.swing.JFrame {


    /**
     * Creates new form frmPantallaInicio
     */
    public FrmPantallaInicio() {
        initComponents();
        this.setTitle("Roll & Code");
        this.btnInicioActionPerformed(null);
        this.setSize(1272, 789);
        this.setLocationRelativeTo(null);
    }
    
    public void pintarPanelPrincipal(JPanel panel){
        jScrollPane.setViewportView(panel);
        panel.setPreferredSize(new Dimension(0,panel.getPreferredSize().height));
        jScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane.revalidate();
        jScrollPane.repaint();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnlFondo = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        JMenuPrincipal = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        btnInicio = new javax.swing.JMenu();
        btnComandas = new javax.swing.JMenu();
        btnNuevaComanda = new javax.swing.JMenuItem();
        btnVerComandas = new javax.swing.JMenuItem();
        btnProductos = new javax.swing.JMenu();
        btnVerProductos = new javax.swing.JMenuItem();
        btnNuevoProducto = new javax.swing.JMenuItem();
        btnIngredientes = new javax.swing.JMenu();
        btnVerIngredientes = new javax.swing.JMenuItem();
        btnNuevoIngrediente = new javax.swing.JMenuItem();
        btnClientesFrecuentes = new javax.swing.JMenu();
        btnBuscarCliente = new javax.swing.JMenuItem();
        btnNuevoCliente = new javax.swing.JMenuItem();
        btnReportes = new javax.swing.JMenu();
        btnReporteClientes = new javax.swing.JMenuItem();
        btnReporteComandas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(247, 242, 239));
        pnlFondo.setLayout(new javax.swing.BoxLayout(pnlFondo, javax.swing.BoxLayout.LINE_AXIS));
        pnlFondo.add(jScrollPane);

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        JMenuPrincipal.setBackground(new java.awt.Color(249, 205, 204));
        JMenuPrincipal.setPreferredSize(new java.awt.Dimension(75, 80));

        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        jMenu8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu8.setMinimumSize(new java.awt.Dimension(130, 50));
        jMenu8.setPreferredSize(new java.awt.Dimension(30, 50));
        JMenuPrincipal.add(jMenu8);

        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicio.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setPreferredSize(new java.awt.Dimension(80, 50));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        JMenuPrincipal.add(btnInicio);

        btnComandas.setText("Comandas");
        btnComandas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComandas.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnComandas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComandas.setMinimumSize(new java.awt.Dimension(130, 50));
        btnComandas.setPreferredSize(new java.awt.Dimension(130, 50));

        btnNuevaComanda.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnNuevaComanda.setText("Crear comanda");
        btnNuevaComanda.setPreferredSize(new java.awt.Dimension(190, 45));
        btnComandas.add(btnNuevaComanda);

        btnVerComandas.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnVerComandas.setText("Ver comandas ");
        btnVerComandas.setPreferredSize(new java.awt.Dimension(190, 45));
        btnComandas.add(btnVerComandas);

        JMenuPrincipal.add(btnComandas);

        btnProductos.setText("Productos");
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setPreferredSize(new java.awt.Dimension(120, 50));

        btnVerProductos.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnVerProductos.setText("Ver productos");
        btnVerProductos.setPreferredSize(new java.awt.Dimension(190, 45));
        btnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProductosActionPerformed(evt);
            }
        });
        btnProductos.add(btnVerProductos);

        btnNuevoProducto.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnNuevoProducto.setText("Agregar producto");
        btnNuevoProducto.setPreferredSize(new java.awt.Dimension(200, 45));
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        btnProductos.add(btnNuevoProducto);

        JMenuPrincipal.add(btnProductos);

        btnIngredientes.setText("Ingredientes");
        btnIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngredientes.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnIngredientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngredientes.setPreferredSize(new java.awt.Dimension(130, 50));

        btnVerIngredientes.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnVerIngredientes.setText("Ver Ingredientes");
        btnVerIngredientes.setPreferredSize(new java.awt.Dimension(190, 45));
        btnIngredientes.add(btnVerIngredientes);

        btnNuevoIngrediente.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnNuevoIngrediente.setText("Agregar Ingrediente");
        btnNuevoIngrediente.setPreferredSize(new java.awt.Dimension(220, 45));
        btnIngredientes.add(btnNuevoIngrediente);

        JMenuPrincipal.add(btnIngredientes);

        btnClientesFrecuentes.setText("Clientes Frecuentes");
        btnClientesFrecuentes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientesFrecuentes.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnClientesFrecuentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientesFrecuentes.setPreferredSize(new java.awt.Dimension(200, 50));

        btnBuscarCliente.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.setPreferredSize(new java.awt.Dimension(210, 45));
        btnClientesFrecuentes.add(btnBuscarCliente);

        btnNuevoCliente.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnNuevoCliente.setText("Agregar cliente");
        btnNuevoCliente.setPreferredSize(new java.awt.Dimension(190, 45));
        btnClientesFrecuentes.add(btnNuevoCliente);

        JMenuPrincipal.add(btnClientesFrecuentes);

        btnReportes.setText("Reportes");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReportes.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setMinimumSize(new java.awt.Dimension(130, 50));
        btnReportes.setPreferredSize(new java.awt.Dimension(130, 50));

        btnReporteClientes.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnReporteClientes.setText("Reporte de clientes");
        btnReporteClientes.setPreferredSize(new java.awt.Dimension(210, 45));
        btnReportes.add(btnReporteClientes);

        btnReporteComandas.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        btnReporteComandas.setText("Reporte de comandas");
        btnReporteComandas.setPreferredSize(new java.awt.Dimension(240, 45));
        btnReportes.add(btnReporteComandas);

        JMenuPrincipal.add(btnReportes);

        setJMenuBar(JMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.pintarPanelPrincipal(new PnlPantallaPrincipal(this));
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        this.pintarPanelPrincipal(new PnlNuevoProducto(this));
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        this.pintarPanelPrincipal(new PnlPantallaPrincipal(this));
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnVerProductosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuPrincipal;
    private javax.swing.JMenuItem btnBuscarCliente;
    private javax.swing.JMenu btnClientesFrecuentes;
    private javax.swing.JMenu btnComandas;
    private javax.swing.JMenu btnIngredientes;
    private javax.swing.JMenu btnInicio;
    private javax.swing.JMenuItem btnNuevaComanda;
    private javax.swing.JMenuItem btnNuevoCliente;
    private javax.swing.JMenuItem btnNuevoIngrediente;
    private javax.swing.JMenuItem btnNuevoProducto;
    private javax.swing.JMenu btnProductos;
    private javax.swing.JMenuItem btnReporteClientes;
    private javax.swing.JMenuItem btnReporteComandas;
    private javax.swing.JMenu btnReportes;
    private javax.swing.JMenuItem btnVerComandas;
    private javax.swing.JMenuItem btnVerIngredientes;
    private javax.swing.JMenuItem btnVerProductos;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
