
package itson.presentacion.frames;

/**
 *
 * @author victoria
 */
public class PnlBuscadorProductos extends javax.swing.JPanel {

    private FrmPantallaInicio pantallaInicio;
     
    public PnlBuscadorProductos(FrmPantallaInicio pantallaInicio) {
        initComponents();
        this.pantallaInicio = pantallaInicio;
        pantallaInicio.pintarPanelPrincipal(this);
        pantallaInicio.setTitle("Buscar Productos");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscador = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        txtBuscadorProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        rbNombreProducto = new javax.swing.JRadioButton();
        rbTipoProducto = new javax.swing.JRadioButton();
        pnlProductos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(247, 242, 239));
        setPreferredSize(new java.awt.Dimension(1272, 698));
        setLayout(new java.awt.BorderLayout());

        pnlBuscador.setBackground(new java.awt.Color(247, 242, 239));
        pnlBuscador.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(247, 242, 239));
        pnlHeader.setPreferredSize(new java.awt.Dimension(572, 140));

        lblTitulo1.setFont(new java.awt.Font("STHeiti", 1, 48)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(65, 70, 105));
        lblTitulo1.setText("Productos");

        txtBuscadorProducto.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        txtBuscadorProducto.setBorder(null);

        btnBuscar.setBackground(new java.awt.Color(247, 242, 239));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/buscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbNombreProducto.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        rbNombreProducto.setForeground(new java.awt.Color(65, 70, 105));
        rbNombreProducto.setText("Nombre");

        rbTipoProducto.setFont(new java.awt.Font("STHeiti", 0, 18)); // NOI18N
        rbTipoProducto.setForeground(new java.awt.Color(65, 70, 105));
        rbTipoProducto.setText("Tipo");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 287, Short.MAX_VALUE)
                .addComponent(rbNombreProducto)
                .addGap(147, 147, 147)
                .addComponent(rbTipoProducto)
                .addGap(353, 353, 353))
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(txtBuscadorProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(btnBuscar))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(lblTitulo1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTipoProducto)
                    .addComponent(rbNombreProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(txtBuscadorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar))
        );

        pnlBuscador.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlProductos.setBackground(new java.awt.Color(247, 242, 239));
        pnlBuscador.add(pnlProductos, java.awt.BorderLayout.CENTER);

        add(pnlBuscador, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JRadioButton rbNombreProducto;
    private javax.swing.JRadioButton rbTipoProducto;
    private javax.swing.JTextField txtBuscadorProducto;
    // End of variables declaration//GEN-END:variables
}
