/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.presentacion.frames;

import com.mycompany.dominiorollandcode.dtos.ClienteDTO;
import java.math.BigDecimal;

/**
 *
 * @author 52644
 */
public class PnlInformacionCliente extends javax.swing.JPanel {
    private FrmPantallaInicio frame;
    private PnlBuscarClientes panel;
    /**
     * Creates new form PnlInformacionCliente
     */
    public PnlInformacionCliente(FrmPantallaInicio frame, PnlBuscarClientes panel, ClienteDTO cliente) {
        initComponents();
        this.frame = frame;
        this.panel = panel;
        this.campoNombre.setText(cliente.getNombres());
        this.campoApellidoP.setText(cliente.getApellidoPaterno());
        this.campoApellidoM.setText(cliente.getApellidoMaterno());
        this.campoCorreoElectronico.setText(cliente.getCorreoElectronico());
        this.campoTelefono.setText(cliente.getTelefono());
        this.campoTotalGastado.setText(String.valueOf(cliente.getGastoTotal()));
        this.campoPuntosFidelidad.setText(String.valueOf((cliente.getGastoTotal().divide(BigDecimal.valueOf(20)))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInformacionCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        lblTotalGastado = new javax.swing.JLabel();
        lblPuntosFidelidad = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoCorreoElectronico = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoTotalGastado = new javax.swing.JTextField();
        campoPuntosFidelidad = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        lblInformacionCliente.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblInformacionCliente.setText("Información Cliente");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblApellidoP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidoP.setText("Apellido Paterno");

        lblApellidoM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidoM.setText("Apellido Materno");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setText("Número de Teléfono");

        lblCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorreoElectronico.setText("Correo Electrónico");

        lblTotalGastado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalGastado.setText("Total Gastado");

        lblPuntosFidelidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPuntosFidelidad.setText("Puntos de Fidelidad");

        campoNombre.setEditable(false);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoApellidoP.setEditable(false);

        campoApellidoM.setEditable(false);

        campoCorreoElectronico.setEditable(false);

        campoTelefono.setEditable(false);

        campoTotalGastado.setEditable(false);
        campoTotalGastado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTotalGastadoActionPerformed(evt);
            }
        });

        campoPuntosFidelidad.setEditable(false);

        btnRegresar.setBackground(new java.awt.Color(247, 242, 239));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/btnRegresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTotalGastado, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoNombre)
                                .addComponent(lblCorreoElectronico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPuntosFidelidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTotalGastado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblApellidoM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblApellidoP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInformacionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoApellidoP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoApellidoM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoCorreoElectronico, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoPuntosFidelidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblInformacionCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addGap(4, 4, 4)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidoP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblApellidoM)
                .addGap(5, 5, 5)
                .addComponent(campoApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorreoElectronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalGastado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTotalGastado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPuntosFidelidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoPuntosFidelidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnRegresar)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoTotalGastadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotalGastadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTotalGastadoActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frame.pintarPanelPrincipal(panel);
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoCorreoElectronico;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPuntosFidelidad;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoTotalGastado;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblInformacionCliente;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntosFidelidad;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotalGastado;
    // End of variables declaration//GEN-END:variables
}
