package itson.presentacion.frames;

/**
 *
 * @author victoria
 */
public class PnlPantallaPrincipal extends javax.swing.JPanel {

    
    public PnlPantallaPrincipal(FrmPantallaInicio pantallaInicio) {
        initComponents();
        pantallaInicio.pintarPanelPrincipal(this);
        pantallaInicio.setTitle("RollAndCode");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnAgregarMesas = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 242, 239));
        setPreferredSize(new java.awt.Dimension(1272, 698));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/logo.png"))); // NOI18N

        btnAgregarMesas.setBackground(null);
        btnAgregarMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/btnAgregarMesas.png"))); // NOI18N
        btnAgregarMesas.setBorder(null);
        btnAgregarMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(lblLogo)
                .addContainerGap(430, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarMesas)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblLogo)
                .addGap(36, 36, 36)
                .addComponent(btnAgregarMesas)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMesasActionPerformed
        System.out.println("agregando mesas");
        this.btnAgregarMesas.setEnabled(false);
    }//GEN-LAST:event_btnAgregarMesasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMesas;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
