/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.presentacion.frames;

/**
 *
 * @author 52644
 */
public class PnlRegistrarCliente extends javax.swing.JPanel {

    FrmPantallaInicio frame;

    /**
     * Creates new form PnlRegistrarCliente
     */
    public PnlRegistrarCliente(FrmPantallaInicio frame) {
        initComponents();
        this.frame = frame;
        frame.pintarPanelPrincipal(this);
        frame.setTitle("Registrar Cliente Frecuente");
    }
    public PnlRegistrarCliente(){
        this(new FrmPantallaInicio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        etiquetaRegistrarCliente = new javax.swing.JLabel();
        etiquetaApellidoPaterno = new javax.swing.JLabel();
        etiquetaNombres = new javax.swing.JLabel();
        etiquetaApellidoMaterno = new javax.swing.JLabel();
        etiquetaEmail = new javax.swing.JLabel();
        campoTextoNombres = new javax.swing.JTextField();
        campoTextoApellidoMaterno = new javax.swing.JTextField();
        campoTextoNumeroTelefono = new javax.swing.JTextField();
        campoTextoApellidoPaterno = new javax.swing.JTextField();
        campoTextoEmail = new javax.swing.JTextField();
        etiquetaNumeroTelefono = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

   

        etiquetaRegistrarCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        etiquetaRegistrarCliente.setText("Registrar Cliente");

        etiquetaApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaApellidoPaterno.setText("Apellido Paterno");

        etiquetaNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNombres.setLabelFor(jTextArea1);
        etiquetaNombres.setText("Nombres");

        etiquetaApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaApellidoMaterno.setText("Apellido Materno");

        etiquetaEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaEmail.setText("Email");

        campoTextoApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoApellidoMaternoActionPerformed(evt);
            }
        });

        campoTextoApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoApellidoPaternoActionPerformed(evt);
            }
        });

        etiquetaNumeroTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNumeroTelefono.setText("Número de teléfono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jScrollPane1);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaApellidoPaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaApellidoMaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaNumeroTelefono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoTextoApellidoMaterno)
                    .addComponent(etiquetaRegistrarCliente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextoNombres, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextoApellidoPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextoNumeroTelefono)
                    .addComponent(campoTextoEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombres)
                    .addComponent(campoTextoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaApellidoPaterno))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaApellidoMaterno)
                    .addComponent(campoTextoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTextoNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaNumeroTelefono))
                        .addGap(18, 18, 18)
                        .addComponent(campoTextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiquetaEmail))
                .addContainerGap(86, Short.MAX_VALUE))
        );

 
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoApellidoPaternoActionPerformed

    private void campoTextoApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoApellidoMaternoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PnlRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PnlRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PnlRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PnlRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PnlRegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTextoApellidoMaterno;
    private javax.swing.JTextField campoTextoApellidoPaterno;
    private javax.swing.JTextField campoTextoEmail;
    private javax.swing.JTextField campoTextoNombres;
    private javax.swing.JTextField campoTextoNumeroTelefono;
    private javax.swing.JLabel etiquetaApellidoMaterno;
    private javax.swing.JLabel etiquetaApellidoPaterno;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JLabel etiquetaNombres;
    private javax.swing.JLabel etiquetaNumeroTelefono;
    private javax.swing.JLabel etiquetaRegistrarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
