package itson.presentacion.frames.panelesIndividuales;

import com.mycompany.dominiorollandcode.dtos.IngredienteDTO;
import com.mycompany.negociorollandcode.IIngredientesBO;
import com.mycompany.negociorollandcode.excepciones.IngredienteException;
import itson.presentacion.excepciones.PresentacionException;
import javax.swing.JOptionPane;


/**
 *
 * @author victoria
 */
public class AgregarStock extends javax.swing.JFrame {

    private PnlIngredienteStock IngredienteSeleccionado;
    private IIngredientesBO ingredientesBO;
    private IngredienteDTO ingredienteDTO;
    
    public AgregarStock(PnlIngredienteStock ingredienteSeleccionado, IIngredientesBO ingredientesBO, IngredienteDTO ingredienteDTO) {
        initComponents();
        this.IngredienteSeleccionado = ingredienteSeleccionado;
        this.ingredientesBO = ingredientesBO;
        this.ingredienteDTO = ingredienteDTO;
        this.setLocationRelativeTo(null);
    }

    public Integer obtenerCantidad(){
         if(txtCantidadStock.getText().isBlank() || txtCantidadStock.getText().isEmpty()){
           try {
               throw new PresentacionException("La cantidad de stock no puede estar vacía.");
           } catch (PresentacionException ex) {
               txtCantidadStock.setText("");
               JOptionPane.showMessageDialog(null, ex.getMessage(),"Aviso", JOptionPane.INFORMATION_MESSAGE);
           }
       }
        return Integer.valueOf(this.txtCantidadStock.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtCantidadStock = new javax.swing.JTextField();
        lblSubtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(247, 242, 239));

        btnAceptar.setBackground(new java.awt.Color(247, 242, 239));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/aceptarStock.png"))); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(247, 242, 239));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/cancelarStock.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("STHeiti", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(65, 70, 105));
        lblTitulo.setText("Agregar Stock");

        txtCantidadStock.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        txtCantidadStock.setBorder(null);

        lblSubtitulo.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(65, 70, 105));
        lblSubtitulo.setText("Ingrese la cantidad requerida:");

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblTitulo))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(45, 45, 45)
                                .addComponent(btnAceptar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(lblSubtitulo)
                .addGap(99, 99, 99))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(txtCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
         try {
            
            Integer cantidadStock = this.obtenerCantidad();
            IngredienteDTO ingredienteActualizado = this.ingredientesBO.actualizarStock(ingredienteDTO, cantidadStock);
            IngredienteSeleccionado.setDatosIngrediente(
                    ingredienteActualizado.getNombre(),
                    ingredienteActualizado.getCantidadStock().toString(),
                    ingredienteActualizado.getUnidadMedida().toString()
            );

            JOptionPane.showMessageDialog(
                    null,
                    "Se ha actualizado el stock del ingrediente: " + ingredienteDTO.getNombre(),
                    "Stock Actualizado",
                    JOptionPane.INFORMATION_MESSAGE
            );
            this.dispose();

        } catch (IngredienteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtCantidadStock;
    // End of variables declaration//GEN-END:variables
}
