/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.presentacion.frames.panelesIndividuales;

import com.mycompany.dominiorollandcode.dtos.ClienteDTO;
import com.mycompany.negociorollandcode.IClientesBO;
import itson.presentacion.frames.PnlBuscarClientes;
import java.math.BigDecimal;

/**
 *
 * @author 52644
 */
public class PnlConsultarCliente extends javax.swing.JPanel {

    ClienteDTO clienteDTO;

    /**
     * Creates new form PnlConsultarCliente
     */
    public PnlConsultarCliente(ClienteDTO cliente) {
        initComponents();
        this.clienteDTO = cliente;
        campoNombre.setText(clienteDTO.getNombres());
        campoApellidoPaterno.setText(clienteDTO.getApellidoPaterno());
        campoCorreo.setText(clienteDTO.getCorreoElectronico());
        campoTelefono.setText(clienteDTO.getTelefono());
        campoPuntosFidelidad.setText(String.valueOf(clienteDTO.getGastoTotal().divide(BigDecimal.valueOf(20L))));
        campoApellidoMaterno.setText(cliente.getApellidoMaterno());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campoNombre = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoCorreo = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoTelefono = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoApellidoPaterno = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoPuntosFidelidad = new javax.swing.JTextPane();
        btnSeleccionar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        campoApellidoMaterno = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(249, 205, 204));

        campoNombre.setEditable(false);
        campoNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jScrollPane1.setViewportView(campoNombre);

        campoCorreo.setEditable(false);
        campoCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(campoCorreo);

        campoTelefono.setEditable(false);
        campoTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane3.setViewportView(campoTelefono);

        campoApellidoPaterno.setEditable(false);
        campoApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane4.setViewportView(campoApellidoPaterno);

        campoPuntosFidelidad.setEditable(false);
        campoPuntosFidelidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane5.setViewportView(campoPuntosFidelidad);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        campoApellidoMaterno.setEditable(false);
        campoApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jScrollPane6.setViewportView(campoApellidoMaterno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JTextPane campoApellidoMaterno;
    private javax.swing.JTextPane campoApellidoPaterno;
    private javax.swing.JTextPane campoCorreo;
    private javax.swing.JTextPane campoNombre;
    private javax.swing.JTextPane campoPuntosFidelidad;
    private javax.swing.JTextPane campoTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
