package itson.presentacion.frames.panelesIndividuales;

/**
 *
 * @author victoria
 */
public class PnlProductoComandaSeleccionado extends javax.swing.JPanel {

    /**
     * Creates new form PnlProducto
     */
    public PnlProductoComandaSeleccionado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblTextoPrecio = new javax.swing.JLabel();
        lblSigno = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnAgregarComentario = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 205, 204));
        setPreferredSize(new java.awt.Dimension(200, 241));

        lblTipoProducto.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblTipoProducto.setForeground(new java.awt.Color(65, 70, 105));
        lblTipoProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoProducto.setText("TIPO:");

        lblNombreProducto.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(65, 70, 105));
        lblNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProducto.setText("NombreProducto");

        lblTextoPrecio.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblTextoPrecio.setForeground(new java.awt.Color(65, 70, 105));
        lblTextoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoPrecio.setText("Precio:");

        lblSigno.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblSigno.setForeground(new java.awt.Color(65, 70, 105));
        lblSigno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSigno.setText("$");

        lblPrecio.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(65, 70, 105));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio.setText("0.00");

        btnAgregarComentario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/btnComentario.png"))); // NOI18N
        btnAgregarComentario.setBorder(null);

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/botones/eliminarProducto.png"))); // NOI18N
        btnEliminarProducto.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSigno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnEliminarProducto)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAgregarComentario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTipoProducto)
                .addGap(33, 33, 33)
                .addComponent(lblNombreProducto)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoPrecio)
                    .addComponent(lblSigno)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarComentario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComentario;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSigno;
    private javax.swing.JLabel lblTextoPrecio;
    private javax.swing.JLabel lblTipoProducto;
    // End of variables declaration//GEN-END:variables
}
